import SwiftUI

/// Maps backend icon names to SF Symbols for iOS
struct CategoryIcons {
    /// Returns the SF Symbol name for a given backend icon name
    static func sfSymbol(for iconName: String?) -> String {
        guard let iconName = iconName else {
            return "folder"
        }

        switch iconName {
        // Furniture
        case "armchair": return "chair.lounge"
        case "bed": return "bed.double"
        case "bedDouble": return "bed.double"
        case "bedSingle": return "bed.double"
        case "doorOpen": return "door.left.hand.open"
        case "lamp": return "lamp.desk"
        case "lampDesk": return "lamp.desk"
        case "lampFloor": return "lamp.floor"
        case "sofa": return "sofa"
        case "table": return "table.furniture"
        case "table2": return "table.furniture"

        // Electronics
        case "camera": return "camera"
        case "cctv": return "video"
        case "cpu": return "cpu"
        case "hardDrive": return "internaldrive"
        case "headphones": return "headphones"
        case "keyboard": return "keyboard"
        case "laptop": return "laptopcomputer"
        case "mic": return "mic"
        case "mic2": return "mic.fill"
        case "monitor": return "display"
        case "monitorSpeaker": return "display"
        case "mouse": return "computermouse"
        case "phone": return "phone"
        case "printer": return "printer"
        case "projector": return "videoprojector"
        case "radio": return "radio"
        case "router": return "wifi.router"
        case "smartphone": return "iphone"
        case "speaker": return "hifispeaker"
        case "tablet": return "ipad"
        case "tabletSmartphone": return "ipad.and.iphone"
        case "tv": return "tv"
        case "tv2": return "tv"
        case "video": return "video"
        case "webcam": return "web.camera"
        case "wifi": return "wifi"

        // Tools & Construction
        case "axe": return "hammer"
        case "brush": return "paintbrush"
        case "cog": return "gearshape"
        case "construction": return "hammer"
        case "drill": return "wrench.and.screwdriver"
        case "fan": return "fan"
        case "flashlight": return "flashlight.on.fill"
        case "hammer": return "hammer"
        case "hardHat": return "helmet"
        case "paintbrush": return "paintbrush"
        case "paintBucket": return "paintbrush.pointed"
        case "pipette": return "eyedropper"
        case "plug": return "powerplug"
        case "ruler": return "ruler"
        case "scale": return "scalemass"
        case "scissors": return "scissors"
        case "settings": return "gearshape"
        case "shovel": return "shovel"
        case "thermometer": return "thermometer.medium"
        case "wrench": return "wrench"
        case "zap": return "bolt"

        // Entertainment & Events
        case "cake": return "birthday.cake"
        case "clapperboard": return "film"
        case "drama": return "theatermasks"
        case "gamepad": return "gamecontroller"
        case "gamepad2": return "gamecontroller"
        case "gift": return "gift"
        case "guitar": return "guitars"
        case "laugh": return "face.smiling"
        case "megaphone": return "megaphone"
        case "music": return "music.note"
        case "music2": return "music.note.list"
        case "music3": return "music.quarternote.3"
        case "music4": return "music.note"
        case "partyPopper": return "party.popper"
        case "piano": return "pianokeys"
        case "popcorn": return "popcorn"
        case "ticket": return "ticket"
        case "trophy": return "trophy"

        // Sports & Outdoor
        case "bike": return "bicycle"
        case "dumbbell": return "dumbbell"
        case "footprints": return "figure.walk"
        case "mountain": return "mountain.2"
        case "mountainSnow": return "mountain.2.fill"
        case "sailboat": return "sailboat"
        case "ship": return "ferry"
        case "snowflake": return "snowflake"
        case "sun": return "sun.max"
        case "sunrise": return "sunrise"
        case "sunset": return "sunset"
        case "tent": return "tent"
        case "treeDeciduous": return "tree"
        case "treePine": return "tree"
        case "trees": return "tree"
        case "umbrella": return "umbrella"
        case "waves": return "water.waves"
        case "wind": return "wind"

        // Kitchen & Home
        case "airVent": return "fan"
        case "alarmClock": return "alarm"
        case "bath": return "bathtub"
        case "batteryCharging": return "battery.100.bolt"
        case "blinds": return "blinds.horizontal.closed"
        case "chefHat": return "frying.pan"
        case "cookingPot": return "frying.pan"
        case "coffee": return "cup.and.saucer"
        case "cupSoda": return "takeoutbag.and.cup.and.straw"
        case "droplet": return "drop"
        case "droplets": return "drop.fill"
        case "flame": return "flame"
        case "flower": return "camera.macro"
        case "flower2": return "camera.macro"
        case "heater": return "heater.vertical"
        case "home": return "house"
        case "house": return "house"
        case "iceCream": return "carrot"
        case "lightbulb": return "lightbulb"
        case "microwave": return "microwave"
        case "pizza": return "fork.knife"
        case "refrigerator": return "refrigerator"
        case "sandwich": return "fork.knife"
        case "soup": return "cup.and.saucer"
        case "utensils": return "fork.knife"
        case "utensilsCrossed": return "fork.knife"
        case "vegan": return "leaf"
        case "washingMachine": return "washer"
        case "wine": return "wineglass"

        // Fashion & Accessories
        case "baby": return "figure.and.child.holdinghands"
        case "backpack": return "backpack"
        case "briefcase": return "briefcase"
        case "crown": return "crown"
        case "gem": return "diamond"
        case "glasses": return "eyeglasses"
        case "graduationCap": return "graduationcap"
        case "shirt": return "tshirt"
        case "shoppingBag": return "bag"
        case "shoppingCart": return "cart"
        case "wallet": return "wallet.pass"
        case "watch": return "applewatch"

        // Transport & Vehicles
        case "bus": return "bus"
        case "car": return "car"
        case "carFront": return "car"
        case "forklift": return "truck.box"
        case "fuel": return "fuelpump"
        case "gauge": return "gauge.high"
        case "plane": return "airplane"
        case "planeLanding": return "airplane.arrival"
        case "planeTakeoff": return "airplane.departure"
        case "rocket": return "airplane.departure"
        case "siren": return "light.beacon.max"
        case "train": return "tram"
        case "trainFront": return "tram"
        case "tractor": return "truck.box"
        case "truck": return "truck.box"

        // Medical & Health
        case "activity": return "waveform.path.ecg"
        case "ambulance": return "cross.circle"
        case "bandage": return "bandage"
        case "bone": return "figure.arms.open"
        case "brain": return "brain.head.profile"
        case "cross": return "cross"
        case "eye": return "eye"
        case "heart": return "heart"
        case "heartPulse": return "heart.text.square"
        case "hospital": return "cross.circle"
        case "pill": return "pills"
        case "stethoscope": return "stethoscope"
        case "syringe": return "syringe"

        // Office & Business
        case "archive": return "archivebox"
        case "bookmark": return "bookmark"
        case "calculator": return "plusminus.circle"
        case "calendar": return "calendar"
        case "calendarDays": return "calendar"
        case "clipboardList": return "list.clipboard"
        case "clock": return "clock"
        case "fileText": return "doc.text"
        case "folder": return "folder"
        case "folderOpen": return "folder"
        case "inbox": return "tray"
        case "mail": return "envelope"
        case "mapPin": return "mappin"
        case "newspaper": return "newspaper"
        case "notebookPen": return "note.text"
        case "paperclip": return "paperclip"
        case "penTool": return "pencil"
        case "presentation": return "chart.bar.doc.horizontal"

        // Photography & Media
        case "aperture": return "camera.aperture"
        case "disc": return "opticaldisc"
        case "film": return "film"
        case "focus": return "camera.viewfinder"
        case "frame": return "photo.artframe"
        case "image": return "photo"
        case "imagePlus": return "photo.badge.plus"
        case "scanLine": return "barcode.viewfinder"
        case "sliders": return "slider.horizontal.3"
        case "slidersHorizontal": return "slider.horizontal.3"

        // Art & Design
        case "crop": return "crop"
        case "eraser": return "eraser"
        case "layers": return "square.3.layers.3d"
        case "layout": return "rectangle.3.group"
        case "layoutGrid": return "square.grid.3x3"
        case "palette": return "paintpalette"
        case "pen": return "pencil"
        case "pencil": return "pencil"
        case "penLine": return "pencil.line"
        case "shapes": return "square.on.circle"
        case "square": return "square"
        case "triangle": return "triangle"
        case "type": return "textformat"

        // Nature & Garden
        case "bug": return "ant"
        case "cat": return "cat"
        case "cloud": return "cloud"
        case "cloudRain": return "cloud.rain"
        case "cloudSnow": return "cloud.snow"
        case "cloudSun": return "cloud.sun"
        case "dog": return "dog"
        case "leaf": return "leaf"
        case "moon": return "moon"
        case "rabbit": return "hare"
        case "rainbow": return "rainbow"
        case "shell": return "fossil.shell"
        case "shrub": return "leaf"
        case "sprout": return "leaf"

        // Other / General
        case "alertCircle": return "exclamationmark.circle"
        case "award": return "rosette"
        case "badge": return "person.badge.shield.checkmark"
        case "bell": return "bell"
        case "box": return "cube.box"
        case "boxes": return "shippingbox"
        case "checkCircle": return "checkmark.circle"
        case "circleUser": return "person.circle"
        case "compass": return "safari"
        case "flag": return "flag"
        case "globe": return "globe"
        case "info": return "info.circle"
        case "key": return "key"
        case "link": return "link"
        case "lock": return "lock"
        case "map": return "map"
        case "package": return "shippingbox"
        case "qrCode": return "qrcode"
        case "scanBarcode": return "barcode"
        case "shield": return "shield"
        case "signal": return "antenna.radiowaves.left.and.right"
        case "star": return "star"
        case "tag": return "tag"
        case "target": return "target"
        case "users": return "person.2"

        default:
            return "folder"
        }
    }
}
